### ISSUE TITLE
Accessibility testing

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#10]
@thomasjbradley

Here is this.
<img width="1274" alt="Screen Shot 2020-03-27 at 11 18 53 AM" src="https://user-images.githubusercontent.com/43241133/77771283-e1eca900-701c-11ea-91bd-e0a73dc49432.png">

**Comment by thomasjbradley** [comment]
What did you fix? What problems did you find?

**Comment by hannahhreed** [comment]
The colors in my buttons were rejected and I had to re color for accessibility purposes and then my image colors needed to change because I didn’t like how it looked in sim daltonism.

**Comment by thomasjbradley** [comment]
💯
