### ISSUE TITLE
images

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#11]
@thomasjbradley

Hi Thomas,

I resized my images and re added them into atom but they're not changing sizes on my website? Just wondering why that could be.

As well as i'm not sure where the a tag is that holds the text decoration making the two words gray.

Thanks 
Hannah Reed

**Comment by thomasjbradley** [comment]
*Images—*

Like you smushed and compressed them?

---

`a` tag is in your `theme.css`

**Comment by hannahhreed** [comment]
yes i did, i will try again

**Comment by hannahhreed** [comment]
it's not working
