### ISSUE TITLE
banner

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#3]
@thomasjbradley 

Hi Thomas, 

For some reason my words will not go on my banner. I did the whole lesson and have tried everything not sure whats going on.

Thank you,
Hannah Reed 03

**Comment by thomasjbradley** [comment]
It looks like it’s working. The `banner/banner.html` pattern, right?
And on the homepage (`index.html`)?

**Comment by hannahhreed** [comment]
The banner part is, but the text that's supposed to be on the banner is stuck at the bottom of the page and won't go where it's supposed to on the banner. If that makes sense.

**Comment by thomasjbradley** [comment]
Oh! Okay, I thought you meant the text wasn’t showing properly.

Add the class of `.pin-c` onto the `.banner-content`:
https://github.com/hannahhreed/ecommerce-pattern-library/blob/master/_patterns/banner/banner.html#L3

**Comment by hannahhreed** [comment]
It worked! Awesome thank you!
I Also dmed you in Slack two quizzes i've completed.
