### ISSUE TITLE
banner

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#4]
@thomasjbradley

I forgot to ask one thing, what do i put to add my button beneath the text?

Thank you

**Comment by thomasjbradley** [comment]
You’d need to put the button directly into the pattern itself. Put the button pattern code above here:
https://github.com/hannahhreed/ecommerce-pattern-library/blob/master/_patterns/banner/banner.html#L6

```
{% pattern buttons/basic %}
```

**Comment by hannahhreed** [comment]
Ok perfect thank you.
