### ISSUE TITLE
homepage template

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#6]
@thomasjbradley

Here is my homepage section completed. 

Thank you

**Comment by thomasjbradley** [comment]
Your homepage only has a single banner on it? No other content?

**Comment by hannahhreed** [comment]
What more does it need? Just so I know how to further continue with it.

**Comment by thomasjbradley** [comment]
Featured products?
Sale products?
About the company? Why buy from them?
Shipping?
Selling features?
Email newsletter signup?
