### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#7]
@thomasjbradley

I'm trying to change the laptop card in my product page to the samsung photo and for some reason it won't change. Maybe you'll be able to find a mistake i'm missing. 

Thank you

**Comment by thomasjbradley** [comment]
The code all looks connected properly. Are you getting any errors in Terminal?

**Comment by hannahhreed** [comment]
the only error was from something earlier that i fixed nothing about the product code.

**Comment by thomasjbradley** [comment]
Did you figure this out? I’m seeing the Samsung case now.

**Comment by hannahhreed** [comment]
Yes I did!! Thank you
