### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by hannahhreed** [hannahhreed/ecommerce-pattern-library#9]
@thomasjbradley

Here is the finished version of the homepage

**Comment by hannahhreed** [comment]
I also am having a problem with my header. When i linked the home and blue cases page together it changed them to grey and i can't change them back. Just wondering why.
Thank you

**Comment by thomasjbradley** [comment]
It’s because they originally weren’t `<a>` tags—so when you switched them to make links this CSS started applying:
https://github.com/hannahhreed/ecommerce-pattern-library/blob/master/css/theme.css#L19-L22

**Comment by hannahhreed** [comment]
Ok makes sense. Where is that a tag located?

**Comment by thomasjbradley** [comment]
In your navigation? Like your link tags?
